[package]
name = "naviamold/profilestore"
description = "Periodic DataStore saving solution with session locking"
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
